[package]
name = "bug-report-clap-completion-when-help-contains-special-characters"
version = "0.0.0"
edition = "2021"

[dependencies.clap]
version = "4.1.8"
features = ["derive"]

[dependencies.clap_complete]
version = "4.1.4"
